// Standalone checks of src/rp2040py/native/core/pwm.hpp (see tests/test_core_cpp.py for the flags).
//
// Two parts. (1) The scenarios of pwm_vectors.inc, generated by tests/utils/pwm_cpp_vectors.py from the pure-Python reference (peripherals/_pwm.py): each is a list of operations - register
// writes and reads (through the atomic aliases too), time, a B input changing, a poke of the direction word, reset - replayed against the C++ block and a recording host; everything that
// leaves the block (the interrupt line, the DMA request of a wrapping channel, the pin it changed together with the pin word at that moment, a warning) and every value read must equal the
// reference's, in order, with the simulated time. (2) Directed checks of what the vectors cannot say: a host call that fails (the interrupt line, the DREQ, the pin change, the pin read) leaves
// exactly the state the reference's exception would have, and the clock stops at that alarm; the bus window adapter; detach.
#include <cstdio>
#include <cstring>

#include "pwm.hpp"

using namespace rp2040core;
using namespace rp2040core::pwm_regs;

static int failures = 0;
#define CHECK(cond)                                                              \
    do {                                                                         \
        if (!(cond)) {                                                           \
            std::printf("%s:%d: CHECK failed: %s\n", __FILE__, __LINE__, #cond); \
            ++failures;                                                          \
        }                                                                        \
    } while (0)

enum OpCode { kW = 0, kR, kT, kIn, kSet, kDir, kReset };
enum EvCode { kIrq = 0, kDreq, kPin, kWarn, kRead };

struct Op {
    int code;
    double x;
    uint32_t a;
    uint64_t b;
    int c;
};
struct Ev {
    int code;
    double time;
    uint32_t a;
    uint64_t b;
    uint64_t c;
};
struct Scenario {
    const char* name;
    const Op* ops;
    unsigned op_count;
    const Ev* events;
    unsigned event_count;
};

#include "pwm_vectors.inc"

struct Env {
    static const unsigned kMax = 4096;
    Ev events[kMax];
    unsigned n = 0;
    uint32_t inputs = 0;
    int failed = 0;
    int fail_irq_on = -1, fail_dreq_on = -1, fail_pin_changed_on = -1, fail_pin_read_on = -1;  // fail the Nth call (0-based) of each, -1: never
    int irq_calls = 0, dreq_calls = 0, pin_changed_calls = 0, pin_read_calls = 0;
    int total_at_failure = -1;  // the number of host calls made when a failure was injected
    int total() const { return irq_calls + dreq_calls + pin_changed_calls + pin_read_calls; }
};
static Env env;
static Clock clk;
static PwmBlock* block = nullptr;  // a fresh block for every scenario: init() attaches a channel's alarms to its timer once
#define pwm (*block)

static void add(int code, uint32_t a, uint64_t b, uint64_t c) {
    if (env.n < Env::kMax) env.events[env.n] = Ev{code, clk.nanos(), a, b, c};
    ++env.n;
}

static bool on_irq(void*, bool level) {
    const int call = env.irq_calls++;
    add(kIrq, level ? 1u : 0u, 0, 0);
    if (call == env.fail_irq_on) { env.failed = 1; env.total_at_failure = env.total(); return false; }
    return true;
}
static bool on_dreq(void*, uint32_t channel) {
    const int call = env.dreq_calls++;
    add(kDreq, channel, 0, 0);
    if (call == env.fail_dreq_on) { env.failed = 1; env.total_at_failure = env.total(); return false; }
    return true;
}
static bool on_pin_changed(void*, uint32_t pin) {
    const int call = env.pin_changed_calls++;
    add(kPin, pin, pwm.gpio_value, 0);
    if (call == env.fail_pin_changed_on) { env.failed = 1; env.total_at_failure = env.total(); return false; }
    return true;
}
static bool on_pin_read(void*, uint32_t pin, bool* level) {
    const int call = env.pin_read_calls++;
    if (call == env.fail_pin_read_on) { env.failed = 1; env.total_at_failure = env.total(); return false; }
    *level = ((env.inputs >> pin) & 1u) != 0;
    return true;
}
// The atomic-area message carries no offset in the reference's log, so the vectors do not either.
static void on_warn(void*, uint32_t kind, uint32_t offset, int64_t value) { add(kWarn, kind, kind == kPwmWarnReadAtomicArea ? 0u : offset, static_cast<uint64_t>(value)); }

static void start() {
    if (block != nullptr) {
        block->detach();
        delete block;
    }
    block = new PwmBlock();
    clk.reset();
    env = Env();
    PwmHost host;
    host.irq = on_irq;
    host.dreq = on_dreq;
    host.pin_changed = on_pin_changed;
    host.pin_read = on_pin_read;
    host.warn = on_warn;
    host.failed = &env.failed;
    pwm.init(&clk, host, 125e6);
    CHECK(pwm.reset());
    env.n = 0;  // the construction and the first reset are not part of a scenario
    env.irq_calls = env.dreq_calls = env.pin_changed_calls = env.pin_read_calls = 0;
}

static bool apply(const Op& op) {
    switch (op.code) {
        case kW: return pwm.write_atomic(op.a, static_cast<int64_t>(op.b), static_cast<uint32_t>(op.c));
        case kR: {
            const uint32_t value = pwm.read(op.a);
            add(kRead, op.a, value, 0);
            return true;
        }
        case kT: return clk.tick(op.x);
        case kIn:
            env.inputs = (env.inputs & ~(1u << op.a)) | (static_cast<uint32_t>(op.b) << op.a);
            return pwm.gpio_on_input(op.a);
        case kSet: env.inputs = (env.inputs & ~(1u << op.a)) | (static_cast<uint32_t>(op.b) << op.a); return true;
        case kDir: pwm.gpio_direction = op.a; return true;
        case kReset: return pwm.reset();
        default: return false;
    }
}

static void test_the_scenarios_against_the_reference() {
    const unsigned count = sizeof(kScenarios) / sizeof(kScenarios[0]);
    for (unsigned s = 0; s < count; ++s) {
        const Scenario& sc = kScenarios[s];
        start();
        for (unsigned i = 0; i < sc.op_count; ++i) CHECK(apply(sc.ops[i]));
        const bool same_count = env.n == sc.event_count;
        if (!same_count) std::printf("scenario %s: %u events, expected %u\n", sc.name, env.n, sc.event_count);
        CHECK(same_count);
        const unsigned shown = env.n < sc.event_count ? env.n : sc.event_count;
        for (unsigned i = 0; i < shown && i < Env::kMax; ++i) {
            const Ev& got = env.events[i];
            const Ev& want = sc.events[i];
            if (got.code != want.code || got.time != want.time || got.a != want.a || got.b != want.b || got.c != want.c) {
                std::printf("scenario %s: event %u is {%d, %g, %u, %llu, %llu}, expected {%d, %g, %u, %llu, %llu}\n", sc.name, i, got.code, got.time, got.a,
                            static_cast<unsigned long long>(got.b), static_cast<unsigned long long>(got.c), want.code, want.time, want.a,
                            static_cast<unsigned long long>(want.b), static_cast<unsigned long long>(want.c));
                CHECK(false);
                break;
            }
        }
    }
}

static void free_run_channel0() {
    CHECK(pwm.write(CHN_TOP, 3));
    CHECK(pwm.write(CHN_CC, (1u << 16) | 2u));
    CHECK(pwm.write(CHN_CSR, CSR_EN));
}

static void test_a_failing_interrupt_line_stops_the_clock_at_the_wrap() {
    start();
    env.fail_irq_on = 0;
    free_run_channel0();
    CHECK(!clk.tick(100.0));
    CHECK(clk.nanos() == 32.0);                       // the first wrap: 4 cycles of 8 ns
    CHECK(pwm.int_raw == 1u);                         // set before the line was asked
    CHECK(env.dreq_calls == 0);                       // after the interrupt in the reference: never reached
    CHECK(!pwm.channels[0].alarm_bottom.scheduled());  // a failed callback is not rescheduled
    CHECK(pwm.gpio_value == 0u);                      // the outputs are driven after the interrupt
}

static void test_a_failing_dreq_stops_the_clock_after_the_interrupt() {
    start();
    env.fail_dreq_on = 0;
    free_run_channel0();
    CHECK(!clk.tick(100.0));
    CHECK(clk.nanos() == 32.0 && env.irq_calls == 1 && env.dreq_calls == 1 && pwm.int_raw == 1u && pwm.gpio_value == 0u);
}

static void test_a_failing_pin_change_leaves_the_word_updated() {
    start();
    free_run_channel0();
    env.fail_pin_changed_on = 0;  // the first pin the wrap drives: A1 (pin 0)
    CHECK(!clk.tick(100.0));
    CHECK(clk.nanos() == 32.0);
    CHECK(pwm.gpio_value == 1u);  // the word was set before the host was told; the second pair (pin 16) and B are not reached
    CHECK(!pwm.channels[0].alarm_bottom.scheduled());
}

static void test_a_failing_pin_change_in_a_csr_write_keeps_what_was_stored() {
    start();
    env.fail_pin_changed_on = 0;  // the direction of B1 going low: the first change CSR makes
    CHECK(!pwm.write(CHN_CSR, CSR_EN | (1u << CSR_DIVMODE_SHIFT)));
    PwmChannel& c = pwm.channels[0];
    CHECK(c.csr == (CSR_EN | (1u << CSR_DIVMODE_SHIFT)));  // stored before the direction is touched
    CHECK(c.div_mode == PwmDivMode::kBGated);
    CHECK((pwm.gpio_direction & 2u) == 0u);                 // the word was updated, the host was told and failed
    CHECK(c.timer.mode() == TimerMode::kIncrement);         // the mode is the last thing CSR does: not reached
    CHECK(!c.timer.enable());                               // reset left it stopped; update_enable was not reached
}

static void test_a_failing_pin_read_stops_a_gated_enable() {
    start();
    CHECK(pwm.write(CHN_CSR, CSR_EN | (1u << CSR_DIVMODE_SHIFT)));  // gated: the enable reads the B pins
    env.fail_pin_read_on = env.pin_read_calls;
    CHECK(!pwm.write(CHN_CSR, CSR_EN | (1u << CSR_DIVMODE_SHIFT)));
    CHECK(env.failed == 1);
}

// Whatever the host call that fails, the operation that made it returns false at once and makes no further host call (the reference's exception leaves the rest undone).
static void test_a_failing_host_call_stops_the_operation_at_once() {
    const unsigned count = sizeof(kScenarios) / sizeof(kScenarios[0]);
    for (unsigned s = 0; s < count; ++s) {
        const Scenario& sc = kScenarios[s];
        for (int kind = 0; kind < 4; ++kind) {
            for (int n = 0; n < 30; ++n) {
                start();
                int* fail_on[4] = {&env.fail_irq_on, &env.fail_dreq_on, &env.fail_pin_changed_on, &env.fail_pin_read_on};
                *fail_on[kind] = n;
                bool injected = false;
                for (unsigned i = 0; i < sc.op_count && !injected; ++i) {
                    const bool ok = apply(sc.ops[i]);
                    if (env.failed) {
                        injected = true;
                        CHECK(!ok);
                        CHECK(env.total() == env.total_at_failure);
                    } else {
                        CHECK(ok);
                    }
                }
                if (injected) CHECK(pwm.failed());  // the shell's `failed()` is the shared flag
                if (!injected) break;  // fewer than n+1 calls of this kind in this scenario
            }
        }
    }
}

static void test_double_buffers_are_applied_only_when_the_channel_starts_or_wraps() {
    start();
    PwmChannel& c = pwm.channels[0];
    CHECK(pwm.write(CHN_CC, (3u << 16) | 2u));
    CHECK(c.cc_updated && c.alarm_a.target() == 0 && c.alarm_b.target() == 0);
    CHECK(pwm.write(CHN_CSR, 0));  // a write that neither enables nor wraps applies nothing
    CHECK(c.cc_updated && c.alarm_a.target() == 0);
    CHECK(pwm.write(CHN_CSR, CSR_EN));  // starting applies it
    CHECK(!c.cc_updated && c.alarm_a.target() == 2 && c.alarm_b.target() == 3);
    CHECK(pwm.write(CHN_TOP, 9) && pwm.write(CHN_CC, (5u << 16) | 4u));
    CHECK(pwm.write(CHN_CSR, CSR_EN));  // already enabled: nothing is applied
    CHECK(c.cc_updated && c.top_updated && c.alarm_a.target() == 2);
    CHECK(pwm.write(EN, 0x01u));  // ... and neither does EN on an enabled channel
    CHECK(c.cc_updated && c.top_updated && c.alarm_a.target() == 2);
    CHECK(clk.tick(524300.0));  // the first wrap (TOP is still the reset value 0xFFFF: 65536 cycles of 8 ns) applies both
    CHECK(!c.cc_updated && !c.top_updated && c.alarm_a.target() == 4 && c.alarm_b.target() == 5 && c.timer.top() == 9);
    CHECK(pwm.write(CHN_CSR, 0) && pwm.write(CHN_CC, 0x00010001u));
    CHECK(pwm.write(EN, 0x01u));  // EN enabling a stopped channel applies the buffers too
    CHECK(!c.cc_updated && c.alarm_a.target() == 1 && c.alarm_b.target() == 1);
}

static void test_reset_and_the_edge_modes_stop_the_counter() {
    start();
    PwmChannel& c = pwm.channels[0];
    CHECK(pwm.gpio_direction == 0xFFFFFFFFu && !c.timer.enable() && c.counting_up);
    CHECK(pwm.clock_freq() == 125e6);
    CHECK(pwm.write(CHN_CSR, CSR_EN));
    CHECK(c.timer.enable());
    CHECK(pwm.write(CHN_CSR, CSR_EN | (2u << CSR_DIVMODE_SHIFT)));
    CHECK(!c.timer.enable());  // an edge-counting channel does not run on the clock
    CHECK(pwm.write(CHN_CSR, CSR_EN | (3u << CSR_DIVMODE_SHIFT)));
    CHECK(!c.timer.enable());
    pwm.gpio_direction = 0;
    c.counting_up = false;
    CHECK(pwm.reset());
    CHECK(pwm.gpio_direction == 0xFFFFFFFFu && c.counting_up && !c.timer.enable() && c.csr == 0 && c.top == 0xFFFFu && c.div == 0x10u);
}

static void test_the_window_adapter_and_detach() {
    start();
    const WindowHandler h = pwm.window_handler();
    h.write32(h.ctx, CHN_TOP, 7, kAtomicNormal);
    CHECK(h.read32(h.ctx, CHN_TOP) == 7u);
    h.write32(h.ctx, INTE, 0x0F, kAtomicSet);
    h.write32(h.ctx, INTE, 0x03, kAtomicClear);
    h.write32(h.ctx, INTE, 0xF0, kAtomicXor);
    CHECK(h.read32(h.ctx, INTE) == 0xFCu);
    CHECK(pwm.raw_write_value() == 0xF0);
    free_run_channel0();
    CHECK(clk.has_alarm());
    pwm.detach();
    CHECK(!clk.has_alarm());
}

static void test_a_new_system_clock_retunes_every_counter() {
    start();
    free_run_channel0();
    CHECK(clk.tick(16.0));
    pwm.set_clock_freq(250e6);  // twice as fast: the wraps are now 16 ns apart
    CHECK(pwm.clock_freq() == 250e6);
    CHECK(clk.nanos_to_next_alarm() == 8.0);  // the counter is at 2 of 0..3: two cycles of 4 ns to the wrap (at 125 MHz it would be 16 ns)
}

int main() {
    test_the_scenarios_against_the_reference();
    test_a_failing_interrupt_line_stops_the_clock_at_the_wrap();
    test_a_failing_dreq_stops_the_clock_after_the_interrupt();
    test_a_failing_pin_change_leaves_the_word_updated();
    test_a_failing_pin_change_in_a_csr_write_keeps_what_was_stored();
    test_a_failing_pin_read_stops_a_gated_enable();
    test_a_failing_host_call_stops_the_operation_at_once();
    test_double_buffers_are_applied_only_when_the_channel_starts_or_wraps();
    test_reset_and_the_edge_modes_stop_the_counter();
    test_the_window_adapter_and_detach();
    test_a_new_system_clock_retunes_every_counter();
    if (failures == 0) std::printf("pwm: all checks passed\n");
    return failures == 0 ? 0 : 1;
}
