# Type stub for the compiled Cython module (docs/records/0096-cpp-mcu-core.md, Phase 3): the native gSPI bit shifter of the CYW43 model.
from typing import Any

from rp2040py.native._gpio_pin import GPIOPin

def can_attach(clk: Any, data: Any, cs: Any) -> bool: ...

class GspiShifter:
    def __init__(self, bus: Any, clk: GPIOPin, data: GPIOPin, cs: GPIOPin) -> None: ...
    def detach(self) -> None: ...
    def reset(self) -> None: ...
    @property
    def selected(self) -> bool: ...
    @property
    def bits_in_word(self) -> int: ...
    @property
    def shift_register(self) -> int: ...
    @property
    def responding(self) -> bool: ...
