"""Public facade: prefers the native SIO in `rp2040py.native._sio` (a Cython shell over the C++ block of
`native/core/sio.hpp`, compiled at build time when Cython and a C++ compiler are available - see `setup.py`) when it is
importable, falling back to the plain-Python reference implementation in `_sio.py` otherwise. Every caller imports `RPSIO`
(and the register offsets) from here - never from `_sio.py` or `rp2040py.native` directly. Mirrors `peripherals/timer.py`.

The two are held to identical behaviour by `tests/test_sio_parity.py` (randomized register sessions) and by replaying
recorded firmware sessions (`tests/utils/mmio_trace.py`); the pure-Python class stays the oracle
(docs/records/0096-cpp-mcu-core.md).
"""

from rp2040py._native_gate import native_disabled
from rp2040py._sio import (
    CPUID,
    DIV_CSR,
    DIV_QUOTIENT,
    DIV_REMAINDER,
    DIV_SDIVIDEND,
    DIV_SDIVISOR,
    DIV_UDIVIDEND,
    DIV_UDIVISOR,
    FIFO_RD,
    FIFO_ST,
    FIFO_WR,
    GPIO_HI_IN,
    GPIO_HI_OE,
    GPIO_HI_OE_CLR,
    GPIO_HI_OE_SET,
    GPIO_HI_OE_XOR,
    GPIO_HI_OUT,
    GPIO_HI_OUT_CLR,
    GPIO_HI_OUT_SET,
    GPIO_HI_OUT_XOR,
    GPIO_IN,
    GPIO_MASK,
    GPIO_OE,
    GPIO_OE_CLR,
    GPIO_OE_SET,
    GPIO_OE_XOR,
    GPIO_OUT,
    GPIO_OUT_CLR,
    GPIO_OUT_SET,
    GPIO_OUT_XOR,
    INTERP0_ACCUM0,
    INTERP0_ACCUM0_ADD,
    INTERP0_ACCUM1,
    INTERP0_ACCUM1_ADD,
    INTERP0_BASE0,
    INTERP0_BASE1,
    INTERP0_BASE2,
    INTERP0_BASE_1AND0,
    INTERP0_CTRL_LANE0,
    INTERP0_CTRL_LANE1,
    INTERP0_PEEK_FULL,
    INTERP0_PEEK_LANE0,
    INTERP0_PEEK_LANE1,
    INTERP0_POP_FULL,
    INTERP0_POP_LANE0,
    INTERP0_POP_LANE1,
    INTERP1_ACCUM0,
    INTERP1_ACCUM0_ADD,
    INTERP1_ACCUM1,
    INTERP1_ACCUM1_ADD,
    INTERP1_BASE0,
    INTERP1_BASE1,
    INTERP1_BASE2,
    INTERP1_BASE_1AND0,
    INTERP1_CTRL_LANE0,
    INTERP1_CTRL_LANE1,
    INTERP1_PEEK_FULL,
    INTERP1_PEEK_LANE0,
    INTERP1_PEEK_LANE1,
    INTERP1_POP_FULL,
    INTERP1_POP_LANE0,
    INTERP1_POP_LANE1,
    SPINLOCK0,
    SPINLOCK31,
    SPINLOCK_ST,
)

try:
    if native_disabled():
        raise ImportError("RP2040PY_SKIP_CYTHON=1 set, forcing pure-Python fallback")
    from rp2040py.native._sio import RPSIO
except ImportError:
    from rp2040py._sio import RPSIO

__all__ = (
    "CPUID",
    "DIV_CSR",
    "DIV_QUOTIENT",
    "DIV_REMAINDER",
    "DIV_SDIVIDEND",
    "DIV_SDIVISOR",
    "DIV_UDIVIDEND",
    "DIV_UDIVISOR",
    "FIFO_RD",
    "FIFO_ST",
    "FIFO_WR",
    "GPIO_HI_IN",
    "GPIO_HI_OE",
    "GPIO_HI_OE_CLR",
    "GPIO_HI_OE_SET",
    "GPIO_HI_OE_XOR",
    "GPIO_HI_OUT",
    "GPIO_HI_OUT_CLR",
    "GPIO_HI_OUT_SET",
    "GPIO_HI_OUT_XOR",
    "GPIO_IN",
    "GPIO_MASK",
    "GPIO_OE",
    "GPIO_OE_CLR",
    "GPIO_OE_SET",
    "GPIO_OE_XOR",
    "GPIO_OUT",
    "GPIO_OUT_CLR",
    "GPIO_OUT_SET",
    "GPIO_OUT_XOR",
    "INTERP0_ACCUM0",
    "INTERP0_ACCUM0_ADD",
    "INTERP0_ACCUM1",
    "INTERP0_ACCUM1_ADD",
    "INTERP0_BASE0",
    "INTERP0_BASE1",
    "INTERP0_BASE2",
    "INTERP0_BASE_1AND0",
    "INTERP0_CTRL_LANE0",
    "INTERP0_CTRL_LANE1",
    "INTERP0_PEEK_FULL",
    "INTERP0_PEEK_LANE0",
    "INTERP0_PEEK_LANE1",
    "INTERP0_POP_FULL",
    "INTERP0_POP_LANE0",
    "INTERP0_POP_LANE1",
    "INTERP1_ACCUM0",
    "INTERP1_ACCUM0_ADD",
    "INTERP1_ACCUM1",
    "INTERP1_ACCUM1_ADD",
    "INTERP1_BASE0",
    "INTERP1_BASE1",
    "INTERP1_BASE2",
    "INTERP1_BASE_1AND0",
    "INTERP1_CTRL_LANE0",
    "INTERP1_CTRL_LANE1",
    "INTERP1_PEEK_FULL",
    "INTERP1_PEEK_LANE0",
    "INTERP1_PEEK_LANE1",
    "INTERP1_POP_FULL",
    "INTERP1_POP_LANE0",
    "INTERP1_POP_LANE1",
    "RPSIO",
    "SPINLOCK0",
    "SPINLOCK31",
    "SPINLOCK_ST",
)
