"""Public facade for the SSI (the flash command path): prefers a native implementation when one exists and falls back to the
plain-Python reference in `_ssi.py`. Every caller imports `RPSSI` and the register/command constants from here - never from `_ssi.py`
directly. Mirrors `peripherals/pio.py`/`timer.py`/`dma.py`.

The two are held to identical behaviour by the lockstep differential of `tests/test_ssi_diff.py`; the pure-Python class stays the oracle (docs/records/0096-cpp-mcu-core.md).
"""

from rp2040py._native_gate import native_disabled
from rp2040py.peripherals._ssi import (
    CMD_BLOCK_ERASE,
    CMD_PAGE_PROGRAM,
    CMD_READ_DATA,
    CMD_READ_JEDEC_ID,
    CMD_READ_STATUS_1,
    CMD_READ_STATUS_2,
    CMD_SECTOR_ERASE,
    CMD_WRITE_DISABLE,
    CMD_WRITE_ENABLE,
    CMD_WRITE_STATUS,
    FLASH_BLOCK_SIZE,
    FLASH_PAGE_SIZE,
    FLASH_SECTOR_SIZE,
    JEDEC_ID,
    RPSSI,
    SSI_BAUDR,
    SSI_CTRLR0,
    SSI_CTRLR1,
    SSI_DMACR,
    SSI_DMARDLR,
    SSI_DMATDLR,
    SSI_DR0,
    SSI_ICR,
    SSI_IDR,
    SSI_IMR,
    SSI_ISR,
    SSI_MSTICR,
    SSI_MWCR,
    SSI_RISR,
    SSI_RX_SAMPLE_DLY,
    SSI_RXFLR,
    SSI_RXFTLR,
    SSI_RXOICR,
    SSI_RXUICR,
    SSI_SER,
    SSI_SPI_CTRL_R0,
    SSI_SR,
    SSI_SR_RFNE_BITS,
    SSI_SR_TFE_BITS,
    SSI_SR_TFNF_BITS,
    SSI_SSIENR,
    SSI_TXD_DRIVE_EDGE,
    SSI_TXFLR,
    SSI_TXFTLR,
    SSI_TXOICR,
    SSI_VERSION_ID,
    STATUS2_QE_BIT,
    STATUS_WEL_BIT,
)

try:
    if native_disabled():
        raise ImportError("RP2040PY_SKIP_CYTHON=1 set, forcing pure-Python fallback")
    from rp2040py.native._ssi import RPSSI
except ImportError:
    from rp2040py.peripherals._ssi import RPSSI

__all__ = (
    "CMD_BLOCK_ERASE",
    "CMD_PAGE_PROGRAM",
    "CMD_READ_DATA",
    "CMD_READ_JEDEC_ID",
    "CMD_READ_STATUS_1",
    "CMD_READ_STATUS_2",
    "CMD_SECTOR_ERASE",
    "CMD_WRITE_DISABLE",
    "CMD_WRITE_ENABLE",
    "CMD_WRITE_STATUS",
    "FLASH_BLOCK_SIZE",
    "FLASH_PAGE_SIZE",
    "FLASH_SECTOR_SIZE",
    "JEDEC_ID",
    "RPSSI",
    "SSI_BAUDR",
    "SSI_CTRLR0",
    "SSI_CTRLR1",
    "SSI_DMACR",
    "SSI_DMARDLR",
    "SSI_DMATDLR",
    "SSI_DR0",
    "SSI_ICR",
    "SSI_IDR",
    "SSI_IMR",
    "SSI_ISR",
    "SSI_MSTICR",
    "SSI_MWCR",
    "SSI_RISR",
    "SSI_RXFLR",
    "SSI_RXFTLR",
    "SSI_RXOICR",
    "SSI_RXUICR",
    "SSI_RX_SAMPLE_DLY",
    "SSI_SER",
    "SSI_SPI_CTRL_R0",
    "SSI_SR",
    "SSI_SR_RFNE_BITS",
    "SSI_SR_TFE_BITS",
    "SSI_SR_TFNF_BITS",
    "SSI_SSIENR",
    "SSI_TXD_DRIVE_EDGE",
    "SSI_TXFLR",
    "SSI_TXFTLR",
    "SSI_TXOICR",
    "SSI_VERSION_ID",
    "STATUS2_QE_BIT",
    "STATUS_WEL_BIT",
)
