name: Test MicroPython Releases

on:
  push:
    paths-ignore: &non-code-paths
      - "**.md"
      - "docs/**"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore: *non-code-paths

concurrency:
  group: ci-micropython-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-micropython:
    name: Micropython ${{ matrix.micropython_version }} / ${{ matrix.python_runtime }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        micropython_version:
          - "1.16"
          - "1.17"
          - "1.18"
          - "1.19.1"
          - "1.20.0"
          - "1.21.0"
          - "1.28.0"
        python_runtime:
          - pypy-3.10
          - cpython-3.10
          - cpython-3.14

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync

      # - name: Download MicroPython ${{ matrix.micropython_version }}
      #   run: curl -o micropython.uf2 "https://micropython.org/resources/firmware/RPI_PICO-${VERSION}.uf2"
      #   env:
      #     VERSION: ${{ matrix.micropython_version }}

      - name: Create filesystem
        run: uv run rp2040py mklittlefs littlefs.img tests/micropython/main.py

      - name: Create SPI test filesystem
        run: uv run rp2040py mklittlefs littlefs-spi.img tests/micropython/main-spi.py

      - name: Setup Python ${{ matrix.python_runtime }}
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          python-version: ${{ matrix.python_runtime }}

      - name: Test MicroPython ${{matrix.python_runtime}}-${{ matrix.micropython_version }}
        run: timeout 10m uv run --python ${{ matrix.python_runtime }} --no-dev -- python demo/micropython_run.py --image ${{ matrix.micropython_version }} --expect-text "Hello, MicroPython!"
        env:
          PYTHON_JIT: ${{ matrix.python_runtime == 'cpython-3.14' && '1' || '' }}

      - name: Test MicroPython SPI ${{matrix.python_runtime}}-${{ matrix.micropython_version }}
        run: timeout 10m uv run --python ${{ matrix.python_runtime }} --no-dev -- python tests/micropython_spi_run.py --image ${{ matrix.micropython_version }} "hello world" "h" "0123456789abcdef0123456789abcdef0123456789abcdef"
        env:
          PYTHON_JIT: ${{ matrix.python_runtime == 'cpython-3.14' && '1' || '' }}
