name: Pre-commit

on:
  push:
    paths-ignore: &non-code-paths
      - "**.md"
      - "docs/**"
      - "LICENSE"
  pull_request:
    paths-ignore: *non-code-paths
  workflow_dispatch:
  workflow_call:

concurrency:
  group: pre-commit-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: pre-commit run --all-files
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          python-version: "3.10"
          github-token: ${{ github.token }}

      - name: Install pre-commit
        run: uv tool install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure
